name: realty_flutter
description: realty

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.10.0
  google_sign_in: ^4.0.1+3
  firebase_core: ^0.4.0
  #cloud_firestore: ^0.10.1
  firebase_storage: ^3.0.0
  firebase_analytics: ^1.0.4
  flutter_secure_storage: ^3.2.1+1
  path_provider: ^0.5.0+1
  dio: ^2.1.2
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true